<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="BPELtaxCalculator"
     targetNamespace="http://xmlns.oracle.com/OBRProject/OBRProject/BPELtaxCalculator"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:client="http://xmlns.oracle.com/OBRProject/OBRProject/BPELtaxCalculator"
     xmlns:ns1="http://www.excise.go.th"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/top/db_TR"
     xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/db/top/db_LR"
    >
    <plnk:partnerLinkType name="BPELtaxCalculator">
        <plnk:role name="BPELtaxCalculatorProvider" portType="client:BPELtaxCalculator"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:client="http://xmlns.oracle.com/OBRProject/OBRProject/BPELtaxCalculator"
             xmlns:ns1="http://www.excise.go.th" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
             xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/top/db_TR" xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/db/top/db_LR">
            <import namespace="http://www.excise.go.th" schemaLocation="../Schemas/taxCalculator.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:client="http://xmlns.oracle.com/OBRProject/OBRProject/BPELtaxCalculator"
             xmlns:ns1="http://www.excise.go.th" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
             xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/top/db_TR" xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/db/top/db_LR">
            <xsd:import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/db_TR" schemaLocation="../Schemas/db_TR_table.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:client="http://xmlns.oracle.com/OBRProject/OBRProject/BPELtaxCalculator"
             xmlns:ns1="http://www.excise.go.th" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
             xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/top/db_TR" xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/db/top/db_LR">
            <xsd:import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/db_LR" schemaLocation="../Schemas/db_LR_table.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="BPELtaxCalculatorRequestMessage">
        <wsdl:part name="payload" element="ns1:InputSchema"/>
    </wsdl:message>
    <wsdl:message name="BPELtaxCalculatorResponseMessage">
        <wsdl:part name="payload" element="ns1:OutputSchema"/>
    </wsdl:message>
    <wsdl:portType name="BPELtaxCalculator">
        <wsdl:operation name="process">
            <wsdl:input message="client:BPELtaxCalculatorRequestMessage"/>
            <wsdl:output message="client:BPELtaxCalculatorResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
