<wsdl:definitions
     name="db_LR"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OBRProject/OBRProject/db_LR"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OBRProject/OBRProject/db_LR"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/db_LR"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="db_LR_plt" >
    <plt:role name="db_LR_role" >
      <plt:portType name="tns:db_LR_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/db_LR" schemaLocation="../Schemas/db_LR_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="db_LRSelect_inputParameters">
        <wsdl:part name="db_LRSelect_inputParameters" element="top:db_LRSelect_offcode_inccode_CalDateInputParameters"/>
    </wsdl:message>
    <wsdl:message name="LocalrateCollection_msg">
        <wsdl:part name="LocalrateCollection" element="top:LocalrateCollection"/>
    </wsdl:message>
    <wsdl:portType name="db_LR_ptt">
        <wsdl:operation name="db_LRSelect">
            <wsdl:input message="tns:db_LRSelect_inputParameters"/>
            <wsdl:output message="tns:LocalrateCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
